name: release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run shellcheck and publish new release
      id: release 
      run: |
        eval "$(hub alias -s)"
        sudo apt-get install shellcheck;
        shellcheck *.sh
        tag_name="0.0.${GITHUB_RUN_NUMBER}"
        hub release create -m "$tag_name" "$tag_name"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
